#!/usr/bin/env node
/**
 * review-diff.js
 *
 * Called by the git pre-push hook (and check-push-review.js) to review
 * a code diff using the best available backend:
 *
 *   1. gh models run  — if the gh-models CLI extension is installed
 *   2. gh copilot     — writes a prompt to a temp file for interactive use
 *   3. Fallback       — writes a review-request.md for @Reviewer in VS Code
 *
 * Usage:
 *   node scripts/review-diff.js <path-to-diff-file>
 *
 * Output:
 *   <diff-file-basename>_review.md  (in same directory as diff file)
 */

'use strict';

const { execSync, spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const diffFile = process.argv[2];
if (!diffFile || !fs.existsSync(diffFile)) {
  console.error('Usage: node scripts/review-diff.js <diff-file>');
  process.exit(1);
}

const diff = fs.readFileSync(diffFile, 'utf8');
const reviewOutputFile = diffFile.replace(/\.diff$/, '_review.md');

// Truncate very large diffs to keep prompts manageable
const MAX_CHARS = 8000;
const truncatedDiff =
  diff.length > MAX_CHARS
    ? diff.slice(0, MAX_CHARS) + '\n\n... [diff truncated — see full file for remainder]'
    : diff;

const reviewPrompt = `You are an expert code reviewer for a Node.js/Express/Prisma multi-tenant application.

Review the following git diff and provide:
1. **Critical Issues** (bugs, security vulnerabilities, unhandled errors, broken tenant isolation)
2. **Suggestions** (code quality, performance, missing tests)
3. **Verdict**: APPROVED ✅ or CHANGES REQUESTED 🚫

Focus on correctness, security, and maintainability. Skip style/formatting comments.

\`\`\`diff
${truncatedDiff}
\`\`\``;

// ─── Backend 1: gh models ────────────────────────────────────────────────────
function tryGhModels() {
  try {
    const check = spawnSync('gh', ['extension', 'list'], { encoding: 'utf8' });
    if (!check.stdout || !check.stdout.includes('gh-models')) return null;

    console.log('🤖 Using gh-models for review...');
    const result = spawnSync('gh', ['models', 'run', 'gpt-4o-mini', reviewPrompt], {
      encoding: 'utf8',
      timeout: 120_000,
    });
    return result.status === 0 && result.stdout ? result.stdout.trim() : null;
  } catch {
    return null;
  }
}

// ─── Backend 2: gh copilot prompt file ───────────────────────────────────────
function writeGhCopilotPrompt() {
  const promptFile = diffFile.replace(/\.diff$/, '_prompt.txt');
  fs.writeFileSync(promptFile, reviewPrompt);
  return promptFile;
}

// ─── Backend 3: VS Code review request ───────────────────────────────────────
function buildReviewRequest() {
  return `# 🔍 Code Review Request

> **Auto-generated by git pre-push hook.**
> Open this file in VS Code, then start a Copilot Chat and ask **\`@Reviewer\`** to review the diff.

## How to use
1. Open Copilot Chat in VS Code (\`Ctrl+Shift+I\` / \`Cmd+Shift+I\`)
2. Type \`@Reviewer\` to switch to the Reviewer agent
3. Ask: *"Please review the diff at \`${diffFile}\`"*

## Diff Summary
\`\`\`
${diff.split('\n').slice(0, 30).join('\n')}${diff.split('\n').length > 30 ? '\n...' : ''}
\`\`\`

---
*Full diff: \`${diffFile}\`*
`;
}

// ─── Main ─────────────────────────────────────────────────────────────────────
console.log('🔍 Requesting code review...');

const modelReview = tryGhModels();

if (modelReview) {
  const output = [
    '# Code Review',
    '',
    `_Reviewed by: gh-models (gpt-4o-mini)_`,
    `_Diff: ${path.basename(diffFile)}_`,
    `_Date: ${new Date().toISOString()}_`,
    '',
    modelReview,
  ].join('\n');

  fs.writeFileSync(reviewOutputFile, output);
  console.log(`✅ Review complete → ${reviewOutputFile}`);
} else {
  const promptFile = writeGhCopilotPrompt();
  const requestContent = buildReviewRequest();
  fs.writeFileSync(reviewOutputFile, requestContent);

  console.log(`📝 Review request created → ${reviewOutputFile}`);
  console.log(`   Prompt file: ${promptFile}`);
  console.log('   👉 Open in VS Code and use @Reviewer to review the changes.');
  console.log('   Or run: gh models run gpt-4o-mini < ' + promptFile);
}
